cli: temporary downgrade to tokio 0.2.24
Temporary fix for this:
thread 'main' panicked at 'not currently running on the Tokio runtime.'

Need to learn more about new tokio and how to migrate to the new
version.

Signed-off-by: ElXreno <elxreno@gmail.com>